### ISSUE TITLE
Writing to DG doen't work

### ISSUE THREAD

**Issue by danielwoithe** [codygreen/F5-MFA#1]
Hi Cody,
in my setup, the data group is not filled by the ILX.
No timeout, no error ;(
Do you have an idea how to troubleshoot that? 

Thanks in advance.

**Comment by codygreen** [comment]
I'm not able to reproduce this error in my lab.  Can you create the data group and try again?

Under the common partition create a DG named: token_keys

**Comment by danielwoithe** [comment]
Hi Cody. 
I found out that it was related to SSL handshake - I tried to set strict to 'false" but with inverted comma, it fails. Now with strict: false it works fine.
